#!/bin/bash
# vim: set ft=sh:

VERSION="v0.1.0"

#
# env
#
if [[ -f $HOME/.vivimrc ]]; then source $HOME/.vivimrc; fi
VIVIM_PATH=${VIVIM_PATH:="."}

#
# error
#
function error_unknown_command() {
    local command="$1"
    local subcommand="$2"
    echo "error: Unknown subcommand or option \"$subcommand\" for \"$command\"" 1>&2
}

#
# zshrc
#
function zshrc() {
    local zshrc_src="$VIVIM_PATH/zshrc/.zshrc"
    local zshrc_dst="$HOME/.zshrc"

    case "$1" in
        help | --help | -H)
            zshrc_help
            ;;
        diff)
            zshrc_diff $zshrc_src $zshrc_dst
            ;;
        edit)
            zshrc_edit $zshrc_src
            ;;
        import)
            zshrc_import $zshrc_src $zshrc_dst
            ;;
        export)
            zshrc_export $zshrc_src $zshrc_dst
            ;;
        *)
            error_unknown_command "vivimctl zshrc" "$1"
            exit 1
            ;;
    esac
}

function zshrc_help() {
cat << EOF | column -t -s '|'
SUBCOMMAND|DESCRIPTION
diff|Compare .zshrc file for current git repository and home directory.
edit|Edit .zshrc file in VIVIM_PATH
export|Export .zshrc file from current git repository to home directory.
import|Import .zshrc file from home directory to current git repository.
EOF
}

function zshrc_diff() {
    local zshrc_src="$1"
    local zshrc_dst="$2"

    colordiff "$zshrc_dst" "$zshrc_src" \
        && echo "zshrc synced with '$HOME/.zshrc'"
}

function zshrc_import() {
    local zshrc_src="$1"
    local zshrc_dst="$2"

    mv "$zshrc_src" "$zshrc_src.bak"
    cp -v "$zshrc_dst" "$zshrc_src"
}

function zshrc_export() {
    local zshrc_src="$1"
    local zshrc_dst="$2"

    mv "$zshrc_dst" "$zshrc_dst.bak"
    cp -v "$zshrc_src" "$zshrc_dst"
}

function zshrc_edit() {
    local zshrc_src="$1"
    vi $zshrc_src
    echo "Do 'vivimctl export' and 'source ~/.zshrc' to export and source .zshrc in home directory"
}

#
# install
#
function install() {
    case "$1" in
        "")
            local vivim_abs_path=$(cd $VIVIM_PATH && pwd)
            local vivim_install_path="/usr/local/bin/vivimctl"
            echo "VIVIM_PATH='$vivim_abs_path'" > $HOME/.vivimrc
            sudo ln -sf $vivim_abs_path/vivimctl /usr/local/bin/vivimctl && echo "vivimctl installed."
            ;;
        *)
            echo "error: No subcommand or option available for command \"vivimctl install\""
            exit 1
            ;;
    esac
}

#
# pull
#
function pull() {
    case "$1" in
        "")
            pushd $VIVIM_PATH &> /dev/null
            git pull origin main
            popd &> /dev/null
            ;;
        *)
            echo "error: No subcommand or option available for command \"vivimctl pull\""
            exit 1
            ;;
    esac
}

#
# main
#
function main() {
    case "$1" in
        zshrc)
            zshrc $2
            ;;
        install)
            install $2
            ;;
        pull)
            pull $2
            ;;
        help | --help | -H)
            main_help
            ;;
        version | --version | -V)
            main_version
            ;;
        *)
            error_unknown_command "vivimctl" "$1"
            exit 1
            ;;
    esac
}

function main_help() {
cat << EOF | column -t -s '|'
SUBCOMMAND|DESCRIPTION
install|Install vivimctl by creating symlink in /usr/bin
pull|Pull vivim git repository from main branch for origin
version (--version, -V)|Print VIVIMCTL version
zshrc|Manage zsh configuration file (zshrc)
EOF
}

function main_version() {
cat << EOF
VIVIMCTL version $VERSION

VIVIM directory path: $VIVIM_PATH
EOF
}

main $@
