#!/bin/bash
# vim: set ft=sh:

function zshrc() {
    local zshrc_src="./zshrc/.zshrc"
    local zshrc_dst="$HOME/.zshrc"

    case "$1" in
        diff)
            zshrc_diff $zshrc_src $zshrc_dst
            ;;
        import)
            zshrc_import $zshrc_src $zshrc_dst
            ;;
        export)
            zshrc_export $zshrc_src $zshrc_dst
            ;;
        *)
            echo "Unknown sub-command for zshrc '$1'" 1>&2
            exit 1
            ;;
    esac
}

function zshrc_import() {
    local zshrc_src="$1"
    local zshrc_dst="$2"

    mv "$zshrc_src" "$zshrc_src.bak"
    mv "$zshrc_dst" "$zshrc_src"
}

function zshrc_export() {
    local zshrc_src="$1"
    local zshrc_dst="$2"

    mv "$zshrc_dst" "$zshrc_dst.bak"
    mv "$zshrc_src" "$zshrc_dst"
}

function zshrc_diff() {
    local zshrc_src="$1"
    local zshrc_dst="$2"

    colordiff "$zshrc_src" "$zshrc_dst" \
        && echo "zshrc synced with '$HOME/.zshrc'"
}

function main() {
    case "$1" in
        zshrc)
            zshrc $2
            ;;
        *)
            echo "Unknown sub-command '$1'" 1>&2
            exit 1
            ;;
    esac
}

main $@
